name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Current directory:"
          pwd
          echo
          echo "Files in current directory:"
          ls -la
          echo
          echo "Find all Dockerfiles:"
          find . -name "Dockerfile"
          echo
          echo "Git status:"
          git status

      - name: Build Docker image
        run: docker build . -f Dockerfile -t my-image-name:latest